#:schema node_modules/wrangler/config-schema.json
name = 'student-management'
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = [ "nodejs_compat" ]

[observability]
enabled = true
head_sampling_rate = 1 # optional. default = 1.

[vars]
DATABASE_URL="postgresql://tuan908:ch4PFt5iGABb@ep-delicate-hill-a1gaqjlb-pooler.ap-southeast-1.aws.neon.tech/student-management?sslmode=require"
