import theme from "@/lib/styles/theme";
import {CssBaseline} from "@mui/material";
import {AppRouterCacheProvider} from "@mui/material-nextjs/v14-appRouter";
import {ThemeProvider} from "@mui/material/styles";
import type {Metadata} from "next";
import "./globals.css";

export const metadata: Metadata = {
    title: {
        default: "OJT",
        template: "%s | OJT",
    },
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className="text-default">
                <AppRouterCacheProvider options={{enableCssLayer: true}}>
                    <ThemeProvider theme={theme}>
                        <CssBaseline />
                        {children}
                    </ThemeProvider>
                </AppRouterCacheProvider>
            </body>
        </html>
    );
}
