spring.application.name=spring-api
# Application:
spring.main.lazy-initialization=true
server.port=8082
spring.threads.virtual.enabled=true

# DataSource
spring.datasource.url=jdbc:postgresql://ep-wandering-fog-71031792-pooler.ap-southeast-1.aws.neon.tech/student-management?user=tuan908&password=ch4PFt5iGABb&sslmode=require
spring.datasource.username=tuan908
spring.datasource.password=1

# HikariCP Connection Pool
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000

# DataSource - JPA's specific configuration:
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.jakarta.persistence.sharedCache.mode=ALL
spring.data.jpa.repositories.bootstrap-mode=lazy

# Hibernate Naming and Performance
spring.jpa.properties.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
spring.jpa.properties.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
spring.jpa.properties.hibernate.jdbc.batch_size=50
spring.jpa.properties.hibernate.order_updates=true
spring.jpa.properties.hibernate.order_inserts=true

# Database Dialect and SQL Logging (Conditional)
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# SQL statements and parameters
logging.level.org.hibernate.SQL=debug
logging.level.org.hibernate.orm.jdbc.bind=trace
# Statistics and slow queries
logging.level.org.hibernate.stat=debug
logging.level.org.hibernate.SQL_SLOW=info
# 2nd Level Cache
logging.level.org.hibernate.cache=debug

# Spring Security with OAuth2:
spring.security.oauth2.client.registration.google.client-id=111387214101-kqa24818do33c3q5t7cgdio841sg4v6a.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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

# Logging Configuration (Production-Ready)
logging.level.root=WARN
logging.level.org.springframework.web=ERROR
logging.level.org.hibernate=ERROR

# Actuator Configurations
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# JWT:
jwt.token.secret=nUD4FzMAeCTHBfEZHJOaDsljyjdt3gIBxE5PxNnADJ6PkTMCF3O7sDKD5NEhTZdN9gSQPfb3RTtkpfCz7qmAJExjMYxTrmbxwDMJ
jwt.token.expiration=86400000
jwt.refresh.secret=d2ouR4PIv96wuEm20YOeDsljyjdt3gIBxE5PxNnADJ6PkTMCF3O7sDKD5NEhTZdN9gSQPfb3RTtkpfCz7qmAJExjMYxTrmbxwDMJ
jwt.refresh.expiration=2592000000

# Redis
spring.data.redis.ssl.enabled=true
spring.data.redis.host=select-satyr-54572.upstash.io
spring.data.redis.port=6379
spring.data.redis.password=AdUsAAIjcDE4Mzc5NDZmNzQxNDU0NDNiOTEyOTdlYzc5MDMwMzcwZXAxMA